### PR TITLE
Moving over to `crypton` backend

### PR DESCRIPTION
**Pull request by Vlix**
Also updated a bit of the CI settings, since we got GHC 9.6.6 now.
And the `haskell/actions/setup` is now deprecated, using `haskell-actions/setup` now.

### CODE REVIEW

**Comment by Vlix** [comment]
#78

**Review by cdepillabout — APPROVED** [review]
LGTM, thanks!

If we know the OSX GitHub Actions fail, we could always just remove them as well.  No sense in keeping them around if we always just ignore them.

**Comment by Vlix** [comment]
I'd like the OSX actions to just work, so I don't want to remove them... but I didn't have time to actually look into it. :/

**Comment by Vlix** [comment]
@cdepillabout version `3.1.0.0` is now pushed to hackage, ready for nightly

**Pull request merged**
