### PR TITLE
bytestring deps constraint can also be bumped

### PR DESCRIPTION
**Pull request by Vlix**

### CODE REVIEW

**Comment by Vlix** [comment]
Basically just bumped to `bytestring <0.12`. Nothing will be building on GHC 9.2.2 with `base64` still not updated, but at least we'll have the correct constraints. Won't make this into a new release either, we can just revise hackage releases.

**Comment by cdepillabout** [comment]
Sorry I missed this!  Thanks!

**Comment by cdepillabout** [comment]
I added a revision on Hackage for this: https://hackage.haskell.org/package/password-3.0.1.0/revisions/

**Comment by Vlix** [comment]
> Sorry I missed this! Thanks!

Hey, no worries. I also forgot about this 😅

**Pull request merged**
