### PR TITLE
Validation documentation update

### PR DESCRIPTION
**Pull request by Vlix**
New branch created from @agentultra's contribution.

Adding link to the NIST publication and changing the defaults for the password validation.

### CODE REVIEW

**Review by cdepillabout — APPROVED** [review]
LGTM!

**Comment by Vlix** [comment]
I finished up this documentation too, but I'd like one last review on any spelling/typos, AND not sure if a PATCH update would be enough? We made the `defaultPasswordPolicy` more lax, so some passwords that would not be valid with `password-2.1.0.0` might suddenly be valid if the user only used the default policy. Would that be enough to necessitate a `2.1.1.0` increase? (Or even a `2.2.0.0`?)
After that is decided we can do a release.

**Comment by Vlix** [comment]
I decided on upping `password` to `2.1.1.0`, since changing the internals of `defaultPasswordPolicy` is not just a patch, and it's not really breaking the API or anything.

Will double check spelling and then upload to stackage, unless there are any new objections.

**Review by cdepillabout — APPROVED** [review]
This looks really good.  Very easy to understand.

Version bumps sound good!

**Comment by Vlix** [comment]
I've uploaded `password-2.1.1.0` and `password-instances-2.0.0.2` to hackage.

**Pull request merged**
