### PR TITLE
Argon2 fix

### PR DESCRIPTION
**Pull request by Vlix**
Should fix the inconsistency pointed out in #42

### CODE REVIEW

**Comment by Vlix** [comment]
Ok, finally, all other PRs are merged.
This is the final PR before we release 3.0.0.0 and `password-types`

**Comment by jdoe0000000** [comment]
> Also, I didn't credit the reporter of #42 since it seems to be a throwaway account. (jdoe0000000)

I can confirm that this is a (semi)throwaway account -- I only use once in a while to submit bug reports and minor PRs -- so no need to credit me.

**Review by cdepillabout — APPROVED** [review]
This LGTM!

Thanks for bringing it up @jdoe0000000.

**Comment by Vlix** [comment]
> > Also, I didn't credit the reporter of #42 since it seems to be a throwaway account. (jdoe0000000)
> 
> I can confirm that this is a (semi)throwaway account -- I only use once in a while to submit bug reports and minor PRs -- so no need to credit me.

Thank you for confirming @jdoe0000000  👍 

I've wanted to merge this and release 3.0.0.0 for like 1-2 weeks now, but was a bit busy.
Will clean up the repo and release this weekend, I think.

**Pull request merged**
