### PR TITLE
updated README.md files and made separate README files for hackage

### PR DESCRIPTION
**Pull request by Vlix**

### CODE REVIEW

**Comment by Vlix** [comment]
@cdepillabout Oops, just noticed after uploading to hackage, that it won't do markdown if the README file doesn't end in `.md`. Do you have any idea how to have a different README file on github, vs on hackage?

**Comment by cdepillabout** [comment]
> Do you have any idea how to have a different README file on github, vs on hackage?

Ah, no, I'm not sure how to do this.

Is there a reason for wanting both a `README.md` and a `README` (without `.md`)?  In my experience, Hackage is pretty good at rendering the `README.md`.

**Comment by Vlix** [comment]
Because the `README.md` had a link to `../password`, which does not work on hackage. Hmmm, I wonder if you can have a `README.md` and a `README.MD` file at the same time, check which one GitHub prioritizes, and use the other one for hackage?

**Comment by cdepillabout** [comment]
You could just change the `[password](../password)` link to something like `[password](https://github.com/cdepillabout/password/tree/master/password)`.  I'd be completely fine with that.

Or instead of linking to github, you could just link directly to the `password` package on Hackage.

I think this would be nicer than trying to keep two different READMEs in sync.

**Comment by Vlix** [comment]
I opted for linking to hackage directly. The README in the root folder is better to use for GitHub and using the ones in the library folders for hackage makes the most sense IMHO.

**Pull request merged**
