### PR TITLE
github actions to build using GHC 8.10.4

### PR DESCRIPTION
**Pull request by Vlix**

### CODE REVIEW

**Comment by Vlix** [comment]
Seems the cabal action doesn't have 8.10.4 yet?

**Comment by cdepillabout** [comment]
It should be available by now.

Although I can't find anyway to just easily restart all the failed jobs in the Actions UI.

**Comment by Vlix** [comment]
`actions/setup-haskell` seems to be deprecated, though.
When updating this, probably best to switch to [`haskell/actions`](https://github.com/haskell/actions/tree/main/setup) which `actions/setup-haskell` now advises to use?

**Comment by cdepillabout** [comment]
Oh yeah, good point.  8.10.4 should be available as long as you're using `haskell/actions`.

**Comment by cdepillabout** [comment]
This should be superseded by https://github.com/cdepillabout/password/pull/49.

**Pull request closed without merging**
