### PR TITLE
password: depend on scrypt only iff scrypt flag is enabled

### PR DESCRIPTION
**Pull request by sternenseemann**

### CODE REVIEW

**Comment by sternenseemann** [comment]
(untested)

**Comment by sternenseemann** [comment]
Hm… the `IS_MAC_OS` logic is surely wrong at the moment.

**Comment by Vlix** [comment]
Looks good to me, what would be wrong with it?

**Comment by cdepillabout** [comment]
sterni fixed this in Nixpkgs as well: https://github.com/NixOS/nixpkgs/pull/351305

**Comment by cdepillabout** [comment]
I'm going to close this in favor of https://github.com/cdepillabout/password/pull/85.

**Pull request closed without merging**
