### PR TITLE
Fix haddock documentation cross module links

### LINKED ISSUE #17: hackage-docs: All links in Algorithm section go to 404.
I guess the title is enough.

### PR DESCRIPTION
**Pull request by TristanCacqueray**
## Fix haddock documentation cross module links

Thsi change fixes the cross module references links.

Fixes #17

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
This has been produced using this rule `@"\([^"]*\)"@` -> `@"Data.Password.\1"@`

**Comment by Vlix** [comment]
I think it would be better for the reader to change `"Bcrypt"` into `'Bcrypt'`, so it links to the data types. This way you don't get superfluous `Data.Password.` in the introduction text, but still links to the modules.

**Comment by TristanCacqueray** [comment]
I'm not familiar with this syntax. Trying `@'Data.Password.Bcrypt'@`, `@'Bcrypt'@` or `@Data.Password.'Bcrypt'@` doesn't produce the expected result.
How to get rid of the `Data.Password.` prefix?

**Comment by Vlix** [comment]
Ah right, it doesn't link to external modules automatically. Can you try with `@'Data.Password.Bcrypt.Bcrypt'@`? I'm trying to get the text printed in the haddock to be `Bcrypt`, and link to the `data Bcrypt` declaration in the `Data.Password.Bcrypt` module.

**Comment by TristanCacqueray** [comment]
That seems to work.

**Comment by cdepillabout** [comment]
This looks good to me.  

@TristanCacqueray Thanks for sending this!

@Vlix Thanks for reviewing this.

**Comment by TristanCacqueray** [comment]
Thank you for the suggestions and thanks for using the `good first issue` label :-)

**Pull request merged**
