### PR TITLE
password-instances: switched to " decodeUtf8' "

### PR DESCRIPTION
**Pull request by Vlix**
`PersistField` instance for `PasswordHash` changed to use `decodeUf8'` in case the bytestring is incorrect UTF8.

### CODE REVIEW

**Comment by Vlix** [comment]
Only the nightly build failed, and that's after the tests passed O_o?
Guess this should be fine.

**Review by cdepillabout — APPROVED** [review]
LGTM, thanks for fixing this!

I almost always accidentally use `decodeUtf8` when one of the other variants would be better.

**Comment by Vlix** [comment]
Yeah, I do the same, but if we're gonna be secure, might as well be pedantic about it 🙃

**Comment by cdepillabout** [comment]
I tried restarting the nightly tests one time, and it is still failing.  I don't have any idea what could be going on there.

**Comment by Vlix** [comment]
Merged in `master` and all checks passed. Merging it.

**Pull request merged**
