### PR TITLE
Validating Passwords

### PR DESCRIPTION
**Pull request by Vlix**
This is a new PR using the progress that @HirotoShioi made in the previous PR (#21) but kept in this repo, to adjust before merging into the master branch.

Original PR message
---
This PR introduces Validate module which exposes set of functions that can be used to validate `Password` with given `PasswordPolicy`.

### CODE REVIEW

**Comment by Vlix** [comment]
I had a last skim over the documentation and code, and it looks fine. I think we can just merge this and release `password-2.1.0.0`.

**Comment by Vlix** [comment]
Oh btw, wasn't there something about Travis-CI (at least the .org) going down soon, or I at least heard a lot of people moving away from Travis-CI for open source projects?

**Comment by cdepillabout** [comment]
@Vlix Thanks for finishing this up and pushing it through!

I saw you made a release here on GitHub, but it looks like maybe you haven't uploaded it to Hackage yet?  Did you want me to do this?

**Comment by Vlix** [comment]
Uhmmm, not sure why I didn't. Slipped my mind, I guess.

If it's not too much hassle, please do upload it. Dunno if we want to make a Reddit announcement or something?

**Comment by Vlix** [comment]
@cdepillabout I've uploaded `2.1.0.0` and made a post [here on reddit](https://www.reddit.com/r/haskell/comments/k8tjgb/password2100_password_validation/)

**Comment by cdepillabout** [comment]
@Vlix Thanks for uploading it and sending the post on reddit.  It seemed like it went over really well!

I create a branch for switching to github actions.  I'll probably try to get this working in the next couple of days: https://github.com/cdepillabout/password/pull/33

**Pull request merged**
